<?php
    echo "<nav>\n";
    echo "<ul>\n";
    echo "<li><a href=\"index.php\">Home</a></li>\n";
    echo "<li><a href=\"product.php\">Products</a></li>\n";
    echo "<li><a href=\"enquire.php\">Enquire</a></li>\n";
    echo "<li><a href=\"about.php\">About</a></li>\n";
    echo "<li><a href=\"manager_login.php\">Manager</a></li>\n";
    echo "<li><a href=\"enhancements.php\">Enhancements</a></li>\n";
    echo "<li><a href=\"enhancements2.php\">Enhancements 2</a></li>\n";
    echo "<li><a href=\"enhancements3.php\">Enhancements 3</a></li>\n";
    echo "</ul>\n";
    echo "</nav>\n";
?>
